/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraficoModelos;

/**
 *
 * @author Sergio
 */
public class SistemaDeInventarios extends javax.swing.JFrame {

    /**
     * Creates new form SistemaDeInventarios
     */
    public SistemaDeInventarios() {
        initComponents();
    }
    private java.text.DecimalFormat formato = new java.text.DecimalFormat("0.00");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelSistemaDeInventarios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCa = new javax.swing.JTextField();
        jTextFieldCp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldde = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldeme = new javax.swing.JTextField();
        jLabelQ = new javax.swing.JLabel();
        jTextFieldQ = new javax.swing.JTextField();
        jButtonCalcularQ = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelQ1 = new javax.swing.JLabel();
        jTextFieldN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelQ2 = new javax.swing.JLabel();
        jLabelQ3 = new javax.swing.JLabel();
        jLabelQ4 = new javax.swing.JLabel();
        jButtonCalcularN = new javax.swing.JButton();
        jTextFieldValorT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonCalcularValorT = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCped = new javax.swing.JTextField();
        jButtonCalcularValorCEP = new javax.swing.JButton();
        jLabelQ5 = new javax.swing.JLabel();
        jLabelQ6 = new javax.swing.JLabel();
        jTextFieldValorCC = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButtonCalcularValorCcon = new javax.swing.JButton();
        jButtonCalcularValorCC = new javax.swing.JButton();
        jTextFieldValorCcon = new javax.swing.JTextField();
        jButtonCalcularValorCt = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldValorCr = new javax.swing.JTextField();
        jButtonCalcularValorCR = new javax.swing.JButton();
        jLabelQ8 = new javax.swing.JLabel();
        jButtonCalcularCostoadq = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldValorCt = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldValorQvalidada = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldcostoadq = new javax.swing.JTextField();
        jTextFieldValorCy = new javax.swing.JTextField();
        jButtonCalcularValorCy = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        vtriangulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        valorn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        valordp = new javax.swing.JTextField();
        jButtonCalcularDP = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Q=√2Cp/CaM");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSistemaDeInventarios.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSistemaDeInventarios.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabelSistemaDeInventarios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSistemaDeInventarios.setText("Sistema de Inventarios");
        jPanel1.add(jLabelSistemaDeInventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Deme su valor Ca");

        jLabel2.setText("Deme su valor Cp");

        jLabel3.setText("Deme su valor D");

        jLabel4.setText("Deme su valor M");

        jLabelQ.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelQ.setText("El valor Q es");

        jButtonCalcularQ.setText("Calcular");
        jButtonCalcularQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularQActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Q=√2Cp/CaM");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("N=D/Q");

        jLabelQ1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelQ1.setText("El valor N es");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("T=365/N");

        jLabelQ2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelQ2.setText("Cped: Cp(D/Q)");

        jLabelQ3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelQ3.setText("El valor T es");

        jLabelQ4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelQ4.setText("Cc:Ca*M");

        jButtonCalcularN.setText("Calcular");
        jButtonCalcularN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularNActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("(costo unitario de cada pedido $/pedido)");

        jButtonCalcularValorT.setText("Calcular");
        jButtonCalcularValorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularValorTActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("(costo de compra del articulo $/unidad)");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("(demanda anual de articulos unidades/año)");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("(cantidad economica de pedidos)");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("(% anual de conservacion del inventario)");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("(costo de adquisicion)");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setText("(numeero optimo de pedidos anuales)");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("(ciclo de tiempo de cada pedido)");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setText("(Costo anual de pedidos $/año)");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setText("(Costo unitario de conservar el inventario $/unidad)");

        jTextFieldCped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpedActionPerformed(evt);
            }
        });

        jButtonCalcularValorCEP.setText("Calcular");
        jButtonCalcularValorCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularValorCEPActionPerformed(evt);
            }
        });

        jLabelQ5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelQ5.setText("Ccon: Cc (Q/2)");

        jLabelQ6.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelQ6.setText("Cr: Cep+Ccon");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setText("(costo de compra del articulo $/unidad)");

        jButtonCalcularValorCcon.setText("Calcular");
        jButtonCalcularValorCcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularValorCconActionPerformed(evt);
            }
        });

        jButtonCalcularValorCC.setText("Calcular");
        jButtonCalcularValorCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularValorCCActionPerformed(evt);
            }
        });

        jTextFieldValorCcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorCconActionPerformed(evt);
            }
        });

        jButtonCalcularValorCt.setText("Calcular");
        jButtonCalcularValorCt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularValorCtActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setText("(Costo anual total del inventatio)");

        jTextFieldValorCr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorCrActionPerformed(evt);
            }
        });

        jButtonCalcularValorCR.setText("Calcular");
        jButtonCalcularValorCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularValorCRActionPerformed(evt);
            }
        });

        jLabelQ8.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabelQ8.setText("MODELO DE DESCUENTO POR COMPRAS DE LOTES MAYORES");

        jButtonCalcularCostoadq.setText("Calcular");
        jButtonCalcularCostoadq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularCostoadqActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel23.setText("Q Validada");

        jLabel24.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel24.setText("Cy=Ct+Cadq");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel25.setText("(Q quedada de los intervalos de volumen)");

        jLabel26.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel26.setText("Ct: Cp(D/Q)+CaM(Q/2)");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel27.setText("(costo total del inventario)");

        jTextFieldValorQvalidada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorQvalidadaActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setText("(coloque su valor)");

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel28.setText("Cadq:D*Ca");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel30.setText("(costo total)");

        jTextFieldcostoadq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcostoadqActionPerformed(evt);
            }
        });

        jTextFieldValorCy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorCyActionPerformed(evt);
            }
        });

        jButtonCalcularValorCy.setText("Calcular");
        jButtonCalcularValorCy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularValorCyActionPerformed(evt);
            }
        });

        jButtonRegresar.setText("MENU PRINCIPAL");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jTextField1.setText("Deme el valor λ");
        jTextField1.setBorder(null);

        jLabel10.setText("Deme el valor N");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel11.setText("(no. promedio de sucesos de la muestra)");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel31.setText("(no. sucesos)");

        jButtonCalcularDP.setText("Calcular");
        jButtonCalcularDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularDPActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel32.setText("Distribucion Probabilidad de Poisson");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(70, 70, 70)
                                                .addComponent(jLabel17))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButtonCalcularValorT, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel18))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel30))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelQ3)
                                            .addComponent(jLabelQ))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextFieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelQ1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextFieldValorT, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(386, 386, 386))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel20)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelQ2)
                                        .addGap(135, 135, 135)
                                        .addComponent(jLabelQ4))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextFieldeme, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextFieldde, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jTextFieldCa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(jLabel15))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonCalcularQ, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(34, 34, 34))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(134, 134, 134)
                                                .addComponent(jLabel5))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCped, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jButtonCalcularValorCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(137, 137, 137)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldValorCC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonCalcularValorCC, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(188, 188, 188)
                                        .addComponent(jLabel7)
                                        .addGap(163, 163, 163)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(jButtonCalcularN, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jTextFieldValorQvalidada, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel23)
                                                            .addComponent(jLabel29)
                                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)))
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(vtriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                                    .addComponent(valorn))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButtonCalcularDP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(233, 233, 233))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                .addGap(101, 101, 101)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel24)
                                                                    .addComponent(jButtonCalcularValorCt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addGap(10, 10, 10)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel32)
                                                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jButtonCalcularValorCy, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldValorCy, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                                                                    .addComponent(jTextFieldValorCt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(138, 138, 138))
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(49, 49, 49)
                                                                .addComponent(jLabel26)
                                                                .addGap(31, 31, 31)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jTextFieldcostoadq, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jLabel28)
                                                                    .addComponent(jButtonCalcularCostoadq, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(jLabel16)))))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelQ8)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel25)
                                                        .addGap(31, 31, 31)
                                                        .addComponent(jLabel27))))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelQ5)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jButtonCalcularValorCcon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldValorCcon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelQ6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonCalcularValorCR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextFieldValorCr, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel31)))))
                                .addGap(571, 571, 571))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(valordp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(155, 711, Short.MAX_VALUE)
                                        .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(344, 344, 344)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelQ)
                                    .addComponent(jTextFieldQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelQ1)
                                    .addComponent(jTextFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextFieldCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCalcularQ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCalcularN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelQ3)
                                    .addComponent(jTextFieldValorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addComponent(jButtonCalcularValorT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQ2)
                            .addComponent(jLabelQ4)
                            .addComponent(jLabelQ5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldValorCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldValorCcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButtonCalcularValorCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vtriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel32))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCalcularValorCcon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCalcularValorCC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabelQ8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldValorQvalidada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValorCt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldcostoadq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonCalcularValorCt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonCalcularCostoadq, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldValorCy, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCalcularValorCy, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQ6)
                            .addComponent(jLabel10)
                            .addComponent(valorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCalcularValorCR, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(valordp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCalcularDP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(579, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularValorCyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularValorCyActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        double qv = Double.parseDouble(jTextFieldValorQvalidada.getText());
        ///
        double resultadoct = ((cp * (d / qv)) + ((ca * m) * (qv / 2)));
        double resultadocostoa = d*ca;
        double resultadocy=resultadoct+resultadocostoa;
        String valorcy= formato.format(resultadocy);
        jTextFieldValorCy.setText(valorcy);
        ////

    }//GEN-LAST:event_jButtonCalcularValorCyActionPerformed

    private void jTextFieldValorCyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorCyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorCyActionPerformed

    private void jTextFieldcostoadqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcostoadqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcostoadqActionPerformed

    private void jTextFieldValorQvalidadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorQvalidadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorQvalidadaActionPerformed

    private void jButtonCalcularCostoadqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularCostoadqActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        ///
        double resultadocostoa = d*ca;
        String valorcostoa = formato.format(resultadocostoa);
        jTextFieldcostoadq.setText(valorcostoa);

    }//GEN-LAST:event_jButtonCalcularCostoadqActionPerformed

    private void jButtonCalcularValorCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularValorCRActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        ///

        double resultado0 = ((2) * (cp * d)) / (ca * m);
        double resultadoq = Math.sqrt(resultado0);
        double resultadocep = (cp * (d / resultadoq));
        double resultadocc = ca * m;
        double resultadoccon = (resultadocc * (resultadoq / 2));
        double resultadocr = resultadocep + resultadoccon;
        String valorcr = formato.format(resultadocr);
        jTextFieldValorCr.setText(valorcr);
    }//GEN-LAST:event_jButtonCalcularValorCRActionPerformed

    private void jTextFieldValorCrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorCrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorCrActionPerformed

    private void jButtonCalcularValorCtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularValorCtActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        double qv = Double.parseDouble(jTextFieldValorQvalidada.getText());
        ///
        double resultadoct = ((cp * (d / qv)) + ((ca * m) * (qv / 2)));
        String valorct = formato.format(resultadoct);
        jTextFieldValorCt.setText(valorct);
        //
    }//GEN-LAST:event_jButtonCalcularValorCtActionPerformed

    private void jTextFieldValorCconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorCconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorCconActionPerformed

    private void jButtonCalcularValorCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularValorCCActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());

        double resultadocc = ca * m;
        String valorcc = formato.format(resultadocc);
        jTextFieldValorCC.setText(valorcc);
    }//GEN-LAST:event_jButtonCalcularValorCCActionPerformed

    private void jButtonCalcularValorCconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularValorCconActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());

        double resultado0 = ((2) * (cp * d)) / (ca * m);
        double resultadoq = Math.sqrt(resultado0);
        double resultadocc = ca * m;
        double resultadoccon = (resultadocc * (resultadoq / 2));
        String valorccon = formato.format(resultadoccon);
        jTextFieldValorCcon.setText(valorccon);

    }//GEN-LAST:event_jButtonCalcularValorCconActionPerformed

    private void jButtonCalcularValorCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularValorCEPActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        ///

        double resultado0 = ((2) * (cp * d)) / (ca * m);
        double resultadoq = Math.sqrt(resultado0);
        double resultadocep = (cp * (d / resultadoq));
        String valorcep = formato.format(resultadocep);
        jTextFieldCped.setText(valorcep);
    }//GEN-LAST:event_jButtonCalcularValorCEPActionPerformed

    private void jTextFieldCpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpedActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        ///
        double resultado0 = ((2) * (cp * d)) / (ca * m);
        double resultadoq = Math.sqrt(resultado0);
        double resultadocep = (cp * (d / resultadoq));
        String valorcep = formato.format(resultadocep);
        jTextFieldCped.setText(valorcep);
        ///

    }//GEN-LAST:event_jTextFieldCpedActionPerformed

    private void jButtonCalcularValorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularValorTActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        ///
        double resultado0 = ((2) * (cp * d)) / (ca * m);
        double resultadoq = Math.sqrt(resultado0);
        String valorq = formato.format(resultadoq);
        //
        double resultadon = d / resultadoq;
        String valorn = formato.format(resultadon);
        ///
        double resultadot = 365 / resultadon;
        String valort = formato.format(resultadot);
        jTextFieldValorT.setText(valort);
    }//GEN-LAST:event_jButtonCalcularValorTActionPerformed

    private void jButtonCalcularNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularNActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        ///

        double resultado0 = ((2) * (cp * d)) / (ca * m);
        double resultadoq = Math.sqrt(resultado0);
        String valorq = formato.format(resultadoq);
        //
        double resultadon = d / resultadoq;
        String valorn = formato.format(resultadon);
        jTextFieldN.setText(valorn);
    }//GEN-LAST:event_jButtonCalcularNActionPerformed

    private void jButtonCalcularQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularQActionPerformed
        double ca = Double.parseDouble(jTextFieldCa.getText());
        double cp = Double.parseDouble(jTextFieldCp.getText());
        double m = Double.parseDouble(jTextFieldeme.getText());
        double d = Double.parseDouble(jTextFieldde.getText());
        ///
        
        double resultado0 = ((2) * (cp * d)) / (ca * m);
        double resultadoq = Math.sqrt(resultado0);
        String valorq = formato.format(resultadoq);
        jTextFieldQ.setText(valorq);

    }//GEN-LAST:event_jButtonCalcularQActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
     IndexModelos r = new IndexModelos ();
     r.setVisible(true);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonCalcularDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularDPActionPerformed
        double vt = Double.parseDouble(vtriangulo.getText());
        double n = Double.parseDouble(valorn.getText());
        //
        double factorial = 1;
        while (n > 0) {
            factorial = factorial * n;
            n = n - 1;
        }
        String vn = String.valueOf(n);
        
        valordp.setText(vn);
    }//GEN-LAST:event_jButtonCalcularDPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaDeInventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaDeInventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaDeInventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaDeInventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaDeInventarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularCostoadq;
    private javax.swing.JButton jButtonCalcularDP;
    private javax.swing.JButton jButtonCalcularN;
    private javax.swing.JButton jButtonCalcularQ;
    private javax.swing.JButton jButtonCalcularValorCC;
    private javax.swing.JButton jButtonCalcularValorCEP;
    private javax.swing.JButton jButtonCalcularValorCR;
    private javax.swing.JButton jButtonCalcularValorCcon;
    private javax.swing.JButton jButtonCalcularValorCt;
    private javax.swing.JButton jButtonCalcularValorCy;
    private javax.swing.JButton jButtonCalcularValorT;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelQ;
    private javax.swing.JLabel jLabelQ1;
    private javax.swing.JLabel jLabelQ2;
    private javax.swing.JLabel jLabelQ3;
    private javax.swing.JLabel jLabelQ4;
    private javax.swing.JLabel jLabelQ5;
    private javax.swing.JLabel jLabelQ6;
    private javax.swing.JLabel jLabelQ8;
    private javax.swing.JLabel jLabelSistemaDeInventarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCa;
    private javax.swing.JTextField jTextFieldCp;
    private javax.swing.JTextField jTextFieldCped;
    private javax.swing.JTextField jTextFieldN;
    private javax.swing.JTextField jTextFieldQ;
    private javax.swing.JTextField jTextFieldValorCC;
    private javax.swing.JTextField jTextFieldValorCcon;
    private javax.swing.JTextField jTextFieldValorCr;
    private javax.swing.JTextField jTextFieldValorCt;
    private javax.swing.JTextField jTextFieldValorCy;
    private javax.swing.JTextField jTextFieldValorQvalidada;
    private javax.swing.JTextField jTextFieldValorT;
    private javax.swing.JTextField jTextFieldcostoadq;
    private javax.swing.JTextField jTextFieldde;
    private javax.swing.JTextField jTextFieldeme;
    private javax.swing.JTextField valordp;
    private javax.swing.JTextField valorn;
    private javax.swing.JTextField vtriangulo;
    // End of variables declaration//GEN-END:variables
}
